$(function(){
	$("#loginBtn").click(function(){
		$("#loginForm").submit();
	});
	$("#logoutBtn").click(function(){
		$(location).attr("href","/logoutAction.ifit");
	});
	$("#productWriteBtn").click(function(){
		$(location).attr("href","/product/productWrite.html");
	});
});